---  

-  hosts: control
   tasks:
     - name: download transction_list
       block:
         - get_url:
             url: http://ssssadfgdfgfdsaction_list
             dest: /home/ansible/transaction_list1
         - debug: msg="File downloaded"
       rescue:
         - debug: msg="l33t.com appears to be down.  Try again later."
       always:
         - debug: msg="Attempt completed."


     - name: Handle the error
       block:
         - debug:
           msg: 'I execute normally'
      - name: i force a failure
        command: /bin/false
      - debug:
          msg: 'I never execute, due to the above task failing, :-('
       rescue:
         - debug:
           msg: 'I caught an error, can do stuff here to fix it, :-)'
      