---
- hosts: all
  become: yes
  tasks:
  - name: install nfs 
    yum:
      name: nfs-utils
      state: present
  - name: secure nfs
    service: 
      name: nfs-server
      state: started
      enabled: yes
    
- hosts: nfs
  become: yes
  vars: 
    share_path: /mnt/nfsroot
  tasks:   
  - name: exports
    template:
      src: exports.j2
      dest: /etc/exports 
    notify: update_nfs
  handlers:
    - name: update nfs exports
      command: exportnfs -a
      listen: update_nfs

- hosts: remote
  become: yes
  vars:
    nfs_ip: "{{ hostvars['nfs']['ansible_default_ipv4']['address'] }}"
    nfs_hostname: "{{ hostvars['nfs']['ansible_hostname'] }}"
    vars_files:
      - /home/ansible/user-list.txt
  tasks:
    - name: configure hostsfile
      template:
        src: etc.hosts.j2
        dest: /etc/hosts.nfslab
    - name: get file status
      stat:
        path: /opt/user-agreement.txt
        register: filestat
    - name: debug info
      debug:
        var: filestat
    - name: create users
      user:
        name: "{{ item }}"
      when:  filestat.stat.exists
      loop: "{{ users }}"


