---
- hosts: all
  become: yes
  tasks:
  - name: install nfs 
    yum:
      name: nfs-utils
      state: present
  - name: secure nfs
    service: 
      name: nfs-server
      state: started
      enabled: yes
    
- hosts: nfs
  become: yes
  vars: 
    share_path: /mnt/nfsroot
  tasks:   
  - name: exports
    template:
      src: exports.j2
      dest: /etc/exports 
    notify: update_nfs
  handlers:
    - name: update nfs exports
      command: exportnfs -a
      listen: update_nfs   

